# config.toml
# The config of the game, divided into x parts:
# [requires_restart], [

[requires_restart] # Requires a restart.
# The default tile size (16x16)
# Not a constant because there could be something like
# texture packs that have bigger sizes, i.e. 32x32
# (Note: please don't do that yet)
# Type: long
# Default: 16
defaultTileSize = 16
# The default relative scale
# Is relative so it doesn't appear small in large
# monitors, and again, texture packs that have bigger
# sizes.
# Type: long
# Default: 3
defaultRelativeScale = 3
# Sizes the window automatically per device resolution
# if true.
# Type: boolean
# Default: false
autoWindowSizing = true
# The total columns displayed on the window on startup
# Used if autoWindowSizing is set to false.
# Type: long
# Default: 24
totalDisplayedColumns = 24
# The total rows displayed on the window on startup
# * See totalDisplayedColumns
# Type: long
# Default: 14
totalDisplayedRows = 14

[world_default] # The default options when world creation.
# How many levels should the world have.
# Yeah, it isn't always ThousandMazes, but it's the default
# anyways. Preferrably use a number divisible by 8.
# Irreversible after world creation.
# Type: long
# Default: 1024
worldLevels = 1024