# The default tile size (16x16)
# Not a constant because there could be something like
# texture packs that have bigger sizes, i.e. 32x32
# (Note: please don't do that yet)
# Type: long
# Default: 16
defaultTileSize = 16
# The default relative scale
# Is relative so it doesn't appear small in large
# monitors, and again, texture packs that have bigger
# sizes.
# Type: long
# Default: 3
defaultRelativeScale = 3
# The total columns displayed on the window
# Customizable on the game, cannot figure out how to
# make this flexible.
# Type: long
# Default: 24
totalDisplayedColumns = 24
# The total rows displayed on the window
# * See totalDisplayedColumns
# Type: long
# Default: 14
totalDisplayedRows = 14
# The default FPS cap
# If you have a NASA computer you can change this to
# 10 thousand, but it probably does barely anything.
# Also, you will probably not even see the character.
# Type: long
# Default: 60
fpsCap = 60